# Generated by Django 4.0.1 on 2022-11-13 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrakeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ts', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_acc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('y_acc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('z_acc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ts', models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 13, 10, 45, 19, 841767))),
            ],
        ),
    ]
